[pytest]
disable_test_id_escaping_and_forfeit_all_rights_to_community_support = True
python_files = test_*.py *_test.py
python_classes = Test*
python_functions = test_*
markers=
    users: Маркировка для тестов связанных с пользователями.
    regression: Маркировка для регресионных тестов.
    authentication: Маркировка для аутентификационных тестов.